
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.automacao_excel.automacao;

/**
 *
 * @author andrevinicius
 */
public class TelaPrincipal extends javax.swing.JFrame {
    DirectoryPaths pathSistema = new DirectoryPaths();
    DirectoryPaths pathPrefeitura = new DirectoryPaths();


    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")                         
    private void initComponents() {

        btn_prefeitura = new javax.swing.JButton();
        btn_sistema = new javax.swing.JButton();
        btn_gerar = new javax.swing.JButton();
        cabecalho = new javax.swing.JLabel();
        lbl_sistema = new javax.swing.JLabel();
        lbl_prefeittura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_prefeitura.setFont(new java.awt.Font("Noto Sans Nerd Font", 0, 24)); // NOI18N
        btn_prefeitura.setText("Planilha Prefeitura"); // NOI18N
        btn_prefeitura.setToolTipText("");
        btn_prefeitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prefeituraActionPerformed(evt);
            }
        });

        btn_sistema.setFont(new java.awt.Font("Noto Sans Nerd Font", 0, 24)); // NOI18N
        btn_sistema.setText("Planilha Sistema");
        btn_sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sistemaActionPerformed(evt);
            }
        });

        btn_gerar.setFont(new java.awt.Font("Noto Sans Nerd Font", 0, 24)); // NOI18N
        btn_gerar.setText("Fazer analise");
        btn_gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerarActionPerformed(evt);
            }
        });

        cabecalho.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        cabecalho.setText("Automação de fechamento do ISS");

        lbl_sistema.setFont(new java.awt.Font("Noto Sans Nerd Font", 0, 18)); // NOI18N
        lbl_sistema.setText("Selecionado:");

        lbl_prefeittura.setFont(new java.awt.Font("Noto Sans Nerd Font", 0, 18)); // NOI18N
        lbl_prefeittura.setText("Selecionado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(btn_gerar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(cabecalho)))
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_prefeitura, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_prefeittura, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_sistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_sistema, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cabecalho)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_prefeitura, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sistema, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_prefeittura, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btn_gerar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>                        

    private void btn_sistemaActionPerformed(java.awt.event.ActionEvent evt) {
        this.pathSistema.setPathFile("Selecione a planilha do Sistema");
        lbl_sistema.setText("Selecionado: " + this.pathSistema.getPathFile().getName());

    }                                           

    private void btn_prefeituraActionPerformed(java.awt.event.ActionEvent evt) {
        this.pathPrefeitura.setPathFile("Selecione a planilha da prefeitura");
        lbl_prefeittura.setText("Selecionado: " + this.pathPrefeitura.getPathFile().getName());
    }                                              

    private void btn_gerarActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            new NewUpgrade().openFileToChanger(pathPrefeitura, pathSistema);
            lbl_prefeittura.setText("Selecionado: ");
            lbl_sistema.setText("Selecionado: ");
        }catch(Exception e){
            lbl_prefeittura.setText("Sem arquivos selecionados");
            lbl_sistema.setText("Sem aquivos selecionados");
        }
        /*if(pathPrefeitura == null){
        }else if(pathSistema == null){
        }else{
            new NewUpgrade().openFileToChanger(pathPrefeitura, pathSistema);
        }*/
        pathPrefeitura.redefinePathFile();
        pathSistema.redefinePathFile();
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_gerar;
    private javax.swing.JButton btn_prefeitura;
    private javax.swing.JButton btn_sistema;
    private javax.swing.JLabel cabecalho;
    private javax.swing.JLabel lbl_prefeittura;
    private javax.swing.JLabel lbl_sistema;
    // End of variables declaration                   
}
